/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Home;

import Cuerpotecnico.VistaCuerpotecnico;
import Dirigentes.VistaDirigente;
import Empleados.VistaEmpleado;
import Futbolistas.VistaFutbolistas;
import Instalaciones.VistaInstalaciones;
import Lesiones.VistaLesiones;
import Medicos.VistaMedicos;
import Partidos.VistaPartidos;
import Socios.VistaSocios;
import Torneos.VistaTorneos;
import javax.swing.JOptionPane;
import mercadotransferencia.VistaMercadotransferencia;

/**
 *
 * @author 12Mat
 */
public class menuprincipal extends javax.swing.JFrame {

    /**
     * Creates new form menuprincipal
     */
    public menuprincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_partidos = new javax.swing.JButton();
        Boton_Futbolistas = new javax.swing.JButton();
        boton_mercadotransferencias = new javax.swing.JButton();
        boton_instalaciones = new javax.swing.JButton();
        boton_cuerpotecnico = new javax.swing.JButton();
        boton_socios = new javax.swing.JButton();
        btn_empleado = new javax.swing.JButton();
        btn_medicos = new javax.swing.JButton();
        btn_lesiones = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_torneos = new javax.swing.JButton();
        Boton_salir = new javax.swing.JButton();
        btn_dirigentes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 150));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_partidos.setBackground(new java.awt.Color(0, 0, 0));
        btn_partidos.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btn_partidos.setForeground(new java.awt.Color(255, 153, 0));
        btn_partidos.setText("Partidos");
        btn_partidos.setToolTipText("");
        btn_partidos.setBorder(null);
        btn_partidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_partidosActionPerformed(evt);
            }
        });
        getContentPane().add(btn_partidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 130, 50));

        Boton_Futbolistas.setBackground(new java.awt.Color(0, 0, 0));
        Boton_Futbolistas.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Boton_Futbolistas.setForeground(new java.awt.Color(255, 153, 0));
        Boton_Futbolistas.setText("Futbolistas");
        Boton_Futbolistas.setBorder(null);
        Boton_Futbolistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_FutbolistasActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_Futbolistas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 130, 50));

        boton_mercadotransferencias.setBackground(new java.awt.Color(0, 0, 0));
        boton_mercadotransferencias.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        boton_mercadotransferencias.setForeground(new java.awt.Color(255, 153, 0));
        boton_mercadotransferencias.setText("Mercado Transferencias");
        boton_mercadotransferencias.setBorder(null);
        boton_mercadotransferencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_mercadotransferenciasActionPerformed(evt);
            }
        });
        getContentPane().add(boton_mercadotransferencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 210, 60));

        boton_instalaciones.setBackground(new java.awt.Color(0, 0, 0));
        boton_instalaciones.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        boton_instalaciones.setForeground(new java.awt.Color(255, 153, 0));
        boton_instalaciones.setText("Instalaciones");
        boton_instalaciones.setBorder(null);
        boton_instalaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_instalacionesActionPerformed(evt);
            }
        });
        getContentPane().add(boton_instalaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 130, 50));

        boton_cuerpotecnico.setBackground(new java.awt.Color(0, 0, 0));
        boton_cuerpotecnico.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        boton_cuerpotecnico.setForeground(new java.awt.Color(255, 153, 0));
        boton_cuerpotecnico.setText("Cuerpo Técnico");
        boton_cuerpotecnico.setBorder(null);
        boton_cuerpotecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cuerpotecnicoActionPerformed(evt);
            }
        });
        getContentPane().add(boton_cuerpotecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 130, 50));

        boton_socios.setBackground(new java.awt.Color(0, 0, 0));
        boton_socios.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        boton_socios.setForeground(new java.awt.Color(255, 153, 0));
        boton_socios.setText("Socios");
        boton_socios.setBorder(null);
        boton_socios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_sociosActionPerformed(evt);
            }
        });
        getContentPane().add(boton_socios, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 130, 50));

        btn_empleado.setBackground(new java.awt.Color(0, 0, 0));
        btn_empleado.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btn_empleado.setForeground(new java.awt.Color(255, 153, 0));
        btn_empleado.setText("Empleados");
        btn_empleado.setBorder(null);
        btn_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_empleadoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 130, 50));

        btn_medicos.setBackground(new java.awt.Color(0, 0, 0));
        btn_medicos.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btn_medicos.setForeground(new java.awt.Color(255, 153, 0));
        btn_medicos.setText("Médicos");
        btn_medicos.setBorder(null);
        btn_medicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_medicosActionPerformed(evt);
            }
        });
        getContentPane().add(btn_medicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 130, 50));

        btn_lesiones.setBackground(new java.awt.Color(0, 0, 0));
        btn_lesiones.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btn_lesiones.setForeground(new java.awt.Color(255, 153, 0));
        btn_lesiones.setText("Lesiones");
        btn_lesiones.setBorder(null);
        btn_lesiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lesionesActionPerformed(evt);
            }
        });
        getContentPane().add(btn_lesiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 130, 50));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Club Atletico Mitre (SdE)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 800, 90));

        btn_torneos.setBackground(new java.awt.Color(0, 0, 0));
        btn_torneos.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btn_torneos.setForeground(new java.awt.Color(255, 153, 0));
        btn_torneos.setText("Torneos");
        btn_torneos.setBorder(null);
        btn_torneos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_torneosActionPerformed(evt);
            }
        });
        getContentPane().add(btn_torneos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 130, 50));

        Boton_salir.setBackground(new java.awt.Color(0, 0, 0));
        Boton_salir.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Boton_salir.setForeground(new java.awt.Color(255, 153, 0));
        Boton_salir.setText("Salir");
        Boton_salir.setBorder(null);
        Boton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_salirActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 170, 60));

        btn_dirigentes.setBackground(new java.awt.Color(0, 0, 0));
        btn_dirigentes.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btn_dirigentes.setForeground(new java.awt.Color(255, 153, 0));
        btn_dirigentes.setText("Dirigentes");
        btn_dirigentes.setBorder(null);
        btn_dirigentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dirigentesActionPerformed(evt);
            }
        });
        getContentPane().add(btn_dirigentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 130, 50));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/mitre-santiago-del-estero-cancha2b.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 800, 510));

        jButton11.setText("Torneos");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 150, -1));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 140, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_partidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_partidosActionPerformed
        VistaPartidos partidos = new VistaPartidos();
        partidos.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_partidosActionPerformed

    private void boton_mercadotransferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_mercadotransferenciasActionPerformed
        VistaMercadotransferencia mercado = new VistaMercadotransferencia();
        mercado.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_boton_mercadotransferenciasActionPerformed

    private void boton_instalacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_instalacionesActionPerformed
        VistaInstalaciones instalaciones = new VistaInstalaciones();
        instalaciones.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_boton_instalacionesActionPerformed

    private void boton_cuerpotecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cuerpotecnicoActionPerformed
        VistaCuerpotecnico cuerpotecnico = new VistaCuerpotecnico();
        cuerpotecnico.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_boton_cuerpotecnicoActionPerformed

    private void boton_sociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_sociosActionPerformed
        VistaSocios socios = new VistaSocios();
        socios.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_boton_sociosActionPerformed

    private void btn_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_empleadoActionPerformed
        VistaEmpleado empleados = new VistaEmpleado();
        empleados.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_empleadoActionPerformed

    private void btn_medicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_medicosActionPerformed
        VistaMedicos medicos = new VistaMedicos();
        medicos.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_medicosActionPerformed

    private void btn_torneosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_torneosActionPerformed
        VistaTorneos torneos = new VistaTorneos();
        torneos.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_torneosActionPerformed

    private void Boton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_salirActionPerformed
        int opcion = JOptionPane.showOptionDialog(null, "Está seguro que desea salir?", "", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Sí", "No"}, this);
        if (opcion == JOptionPane.YES_OPTION) {
            this.dispose();
            System.exit(0);
        }
    }//GEN-LAST:event_Boton_salirActionPerformed

    private void Boton_FutbolistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_FutbolistasActionPerformed
        VistaFutbolistas futbolistas = new VistaFutbolistas();
        futbolistas.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_Boton_FutbolistasActionPerformed

    private void btn_lesionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lesionesActionPerformed
        VistaLesiones lesiones = new VistaLesiones();
        lesiones.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_lesionesActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void btn_dirigentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dirigentesActionPerformed
        VistaDirigente dirigentes = new VistaDirigente();
        dirigentes.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_dirigentesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Futbolistas;
    private javax.swing.JButton Boton_salir;
    private javax.swing.JButton boton_cuerpotecnico;
    private javax.swing.JButton boton_instalaciones;
    private javax.swing.JButton boton_mercadotransferencias;
    private javax.swing.JButton boton_socios;
    private javax.swing.JButton btn_dirigentes;
    private javax.swing.JButton btn_empleado;
    private javax.swing.JButton btn_lesiones;
    private javax.swing.JButton btn_medicos;
    private javax.swing.JButton btn_partidos;
    private javax.swing.JButton btn_torneos;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
